// FontAwesome setup
import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faBars,
  faBasketballBall,
  faBatteryEmpty,
  faBicycle,
  faCalendarAlt,
  faChartLine,
  faCheck,
  faChevronDown,
  faClock,
  faCoins,
  faComments,
  faDownload,
  faDumbbell,
  faFutbol,
  faGift,
  faHeadset,
  faHeart,
  faMapMarkerAlt,
  faMobileAlt,
  faMoon,
  faPlus,
  faRunning,
  faSearch,
  faStar,
  faStore,
  faSwimmer,
  faSwimmingPool,
  faTableTennis,
  faTrophy,
  faUserCheck,
  faUserTie,
  faUserTimes,
  faUsers,
  faVolleyballBall,
} from '@fortawesome/free-solid-svg-icons'

import {
  faApple,
  faFacebook,
  faGooglePlay,
  faInstagram,
  faLinkedin,
  faTwitter,
} from '@fortawesome/free-brands-svg-icons'

// Add icons to the library
library.add(
  // Solid icons
  faRunning,
  faDownload,
  faBars,
  faSearch,
  faUsers,
  faTrophy,
  faMapMarkerAlt,
  faCalendarAlt,
  faChartLine,
  faUserTimes,
  faComments,
  faBatteryEmpty,
  faFutbol,
  faSwimmer,
  faTableTennis,
  faDumbbell,
  faBicycle,
  faBasketballBall,
  faHeart,
  faVolleyballBall,
  faPlus,
  faCoins,
  faGift,
  faStore,
  faSwimmingPool,
  faUserTie,
  faCheck,
  faUserCheck,
  faHeadset,
  faMobileAlt,
  faStar,
  faClock,
  faChevronDown,
  faMoon,
  // Brand icons
  faApple,
  faGooglePlay,
  faFacebook,
  faInstagram,
  faTwitter,
  faLinkedin,
)
