/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as R404RouteImport } from './routes/404'
import { Route as SplatRouteImport } from './routes/$'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authenticatedPromotionsRouteImport } from './routes/(authenticated)/promotions'
import { Route as authenticatedNotificationsRouteImport } from './routes/(authenticated)/notifications'
import { Route as authenticatedMapRouteImport } from './routes/(authenticated)/map'
import { Route as authenticatedEventsRouteImport } from './routes/(authenticated)/events'
import { Route as authenticatedDashboardRouteImport } from './routes/(authenticated)/dashboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedPromotionsRoute = authenticatedPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedNotificationsRoute =
  authenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedMapRoute = authenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedEventsRoute = authenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedDashboardRoute = authenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => authenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof authenticatedRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/login': typeof LoginRoute
  '/dashboard': typeof authenticatedDashboardRoute
  '/events': typeof authenticatedEventsRoute
  '/map': typeof authenticatedMapRoute
  '/notifications': typeof authenticatedNotificationsRoute
  '/promotions': typeof authenticatedPromotionsRoute
}
export interface FileRoutesByTo {
  '/': typeof authenticatedRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/login': typeof LoginRoute
  '/dashboard': typeof authenticatedDashboardRoute
  '/events': typeof authenticatedEventsRoute
  '/map': typeof authenticatedMapRoute
  '/notifications': typeof authenticatedNotificationsRoute
  '/promotions': typeof authenticatedPromotionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/login': typeof LoginRoute
  '/(authenticated)/dashboard': typeof authenticatedDashboardRoute
  '/(authenticated)/events': typeof authenticatedEventsRoute
  '/(authenticated)/map': typeof authenticatedMapRoute
  '/(authenticated)/notifications': typeof authenticatedNotificationsRoute
  '/(authenticated)/promotions': typeof authenticatedPromotionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/404'
    | '/login'
    | '/dashboard'
    | '/events'
    | '/map'
    | '/notifications'
    | '/promotions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/404'
    | '/login'
    | '/dashboard'
    | '/events'
    | '/map'
    | '/notifications'
    | '/promotions'
  id:
    | '__root__'
    | '/'
    | '/(authenticated)'
    | '/$'
    | '/404'
    | '/login'
    | '/(authenticated)/dashboard'
    | '/(authenticated)/events'
    | '/(authenticated)/map'
    | '/(authenticated)/notifications'
    | '/(authenticated)/promotions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  R404Route: typeof R404Route
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/promotions': {
      id: '/(authenticated)/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof authenticatedPromotionsRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/notifications': {
      id: '/(authenticated)/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof authenticatedNotificationsRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/map': {
      id: '/(authenticated)/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof authenticatedMapRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/events': {
      id: '/(authenticated)/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof authenticatedEventsRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/dashboard': {
      id: '/(authenticated)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authenticatedDashboardRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
  }
}

interface authenticatedRouteRouteChildren {
  authenticatedDashboardRoute: typeof authenticatedDashboardRoute
  authenticatedEventsRoute: typeof authenticatedEventsRoute
  authenticatedMapRoute: typeof authenticatedMapRoute
  authenticatedNotificationsRoute: typeof authenticatedNotificationsRoute
  authenticatedPromotionsRoute: typeof authenticatedPromotionsRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedDashboardRoute: authenticatedDashboardRoute,
  authenticatedEventsRoute: authenticatedEventsRoute,
  authenticatedMapRoute: authenticatedMapRoute,
  authenticatedNotificationsRoute: authenticatedNotificationsRoute,
  authenticatedPromotionsRoute: authenticatedPromotionsRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  R404Route: R404Route,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
